@startuml sequence3
title User loads SPA page
participant browser
participant server
browser -> server : HTTP GET https://fullstack-exampleapp.herokuapp.com/spa
return spa.html
browser -> server : HTTP GET https://fullstack-exampleapp.herokuapp.com/main.css
return main.css
browser -> server : HTTP GET https://fullstack-exampleapp.herokuapp.com/spa.js
return spa.js
note over browser
  Send a request for the notes object in the 
  browser js, which just loaded.
end note
browser -> server : HTTP GET https://fullstack-exampleapp.herokuapp.com/data.json
return [{content: "HTML is easy", date: "2019-05-23T17:30:31.098Z"}, ...]
note over browser
  On receiving this, render html
end note
@enduml
