@startuml sequence
title Posting a message to an HTML page
participant browser
participant server
note over browser: The user submits text
...
browser -> server: HTTP POST https://fullstack-exampleapp.herokuapp.com/new_note
browser -> server: HTTP GET https://fullstack-exampleapp.herokuapp.com/notes
return notes.html
browser -> server: HTTP GET https://fullstack-exampleapp.herokuapp.com/main.css
return main.css
browser -> server: HTTP GET https://fullstack-exampleapp.herokuapp.com/main.js
return main.js
note over browser:
  Browser starts executing js-code
  that requests JSON data from the server
end note
browser -> server: HTTP GET https://fullstack-exampleapp.herokuapp.com/data.json
return [{content: "HTML is easy", date: "2019-05-23T17:30:31.098Z"}, ...]
note over browser: Browser executes the event handler that renders the notes
...
@enduml
