@startuml sequence2
title Submitting notes on Single Page Application
participant browser
participant server
...
note over browser
  The user submits text
end note
note over browser
  Browser executes js code and redraws notes
  It also sends a message to the server containing the input text
end note
browser -> server : HTTP POST https://fullstack-exampleapp.herokuapp.com/new_note_spa
return { message: "note created" }
...
@enduml
